spring:
  jpa:
    hibernate:
      ddl-auto: validate

  mail:
    host: smtp.mailgun.org
    username: postmaster@sandbox409b0c2668d045228b8b5d0892bb24ba.mailgun.org

jwt:
  expiration-minutes: 15

nginx:
  require-proxy: true

chatapp:
  email:
    url: "http://TODO:8080"
  rate-limit:
    ip:
      apply-limit: true