spring:
  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.mailgun.org
    username: postmaster@sandbox409b0c2668d045228b8b5d0892bb24ba.mailgun.org

jwt:
  expiration-minutes: 1000

nginx:
  require-proxy: false

chatapp:
  email:
    url: "http://localhost:8080"
  rate-limit:
    ip:
      apply-limit: false
  web-socket:
    allowed-origin: "http://localhost:8080"

logging:
  level:
    com.vincicent.chatapp: DEBUG